### Find all
GET localhost:8080/training/findAll

### Find by name
GET localhost:8080/training/findByName/pull123

### Add Exercise
PUT localhost:8080/training/add-exercise/lat pulldown/pull

### Generate training
POST localhost:8080/training/generate-training?amountOfTime=45&bodyParts=back&bodyParts=chest
